name: "NanoPi R3S Armbian Build Bookworm Current"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - run: "git clone https://github.com/armbian/build && cd build && ./compile.sh BOARD=nanopi-r3s BRANCH=edge RELEASE=bookworm BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_CONFIGURE=no"
  release:
    needs: build-armbian
    runs-on: ubuntu-latest
    steps:
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: Armbian-unofficial_Nanopi_R3S_bookworm_current.img
        path: ./output/images/*.img
