name: Build Ubuntu with AI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git curl xz-utils

    - name: Clone Armbian build repository
      run: git clone --depth=1 --branch=main https://github.com/armbian/build 

    - name: Compile Armbian image
      run: |
        cd build
        ./compile.sh BOARD=nanopi-r3s BRANCH=edge RELEASE=noble BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_CONFIGURE=no

    - name: Compress compiled image
      run: |
        mkdir -p ${{ github.workspace }}/output
        cp -r build/output/images/* ${{ github.workspace }}/output/
        mkdir -p ${{ github.workspace }}/temp-output
        cp -r ${{ github.workspace }}/output/* ${{ github.workspace }}/temp-output/
        tar -cJf ${{ github.workspace }}/output/armbian-image-jammy.tar.xz -C ${{ github.workspace }}/temp-output .

    - name: Upload compressed image
      uses: actions/upload-artifact@v4
      with:
        name: armbian-image
        path: ${{ github.workspace }}/output/armbian-image-jammy.tar.xz
