name: Build Ubuntu Noble Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: ${{ github.workspace }}/output
      TEMP_OUTPUT_DIR: ${{ github.workspace }}/temp-output
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y git curl gzip

    - name: Clone Armbian build repository
      run: git clone --depth=1 --branch=main https://github.com/armbian/build

    - name: Compile Armbian image
      run: |
        cd build
        ./compile.sh BOARD=nanopi-r3s BRANCH=current RELEASE=noble BUILD_MINIMAL=yes BUILD_DESKTOP=no KERNEL_CONFIGURE=no

    - name: Debug output images
      run: ls -R build/output/images/

    - name: Compress compiled image
      run: |
        mkdir -p $OUTPUT_DIR
        cp -r build/output/images/* $OUTPUT_DIR/
        mkdir -p $TEMP_OUTPUT_DIR
        cp -r $OUTPUT_DIR/* $TEMP_OUTPUT_DIR/
        for img in $TEMP_OUTPUT_DIR/*.img; do
          if [ -f "$img" ]; then
            gzip -c "$img" > "$OUTPUT_DIR/$(basename "$img").gz" || echo "Failed to compress $img"
          else
            echo "No .img files found in $TEMP_OUTPUT_DIR"
          fi
        done

    - name: Debug compressed images
      run: ls -R $OUTPUT_DIR

    - name: Fix file permissions
      run: chmod -R +r $OUTPUT_DIR

    - name: Check file sizes against GitHub limits
      id: check_sizes
      run: |
        GITHUB_FILE_LIMIT=500000000  # 500 MB in bytes
        TOTAL_SIZE=0
        for file in $OUTPUT_DIR/*.img.gz; do
          if [ -f "$file" ]; then
            FILE_SIZE=$(stat --format="%s" "$file")
            TOTAL_SIZE=$((TOTAL_SIZE + FILE_SIZE))
            echo "File: $(basename "$file"), Size: $FILE_SIZE bytes"
            if [ "$FILE_SIZE" -gt "$GITHUB_FILE_LIMIT" ]; then
              echo "::warning::File $(basename "$file") exceeds GitHub's 500 MB limit ($FILE_SIZE bytes)"
            fi
          fi
        done
        echo "Total size of all files: $TOTAL_SIZE bytes"
        if [ "$TOTAL_SIZE" -gt 2000000000 ]; then
          echo "::warning::Total artifact size exceeds GitHub's 2 GB limit ($TOTAL_SIZE bytes)"
        fi

    - name: Locate .img.gz file
      id: locate_file
      run: |
        IMG_GZ_FILE=$(find $OUTPUT_DIR -name "*.img.gz" | head -n 1)
        if [ -n "$IMG_GZ_FILE" ]; then
          echo "Found .img.gz file: $IMG_GZ_FILE"
          echo "img_gz_file=$IMG_GZ_FILE" >> $GITHUB_ENV
        else
          echo "::error::No .img.gz files found in $OUTPUT_DIR"
          exit 1
        fi

    - name: Upload compressed image
      if: env.img_gz_file != ''
      uses: actions/upload-artifact@v4
      with:
        name: armbian-image-ubuntu-noble
        path: ${{ env.img_gz_file }}
